FROM node:18-alpine

WORKDIR /app

COPY front-end/package.json ./package.json
# COPY front-end/yarn.lock ./yarn.lock

# RUN yarn install --frozen-lockfile
RUN yarn install

COPY front-end/ ./

EXPOSE 3004

CMD yarn run dev
# CMD  yarn start:dev