FROM node:20.11-alpine

WORKDIR /app

COPY back-end/package.json ./package.json
# COPY back-end/yarn.lock ./yarn.lock

RUN yarn install


COPY back-end/ ./

EXPOSE 3000

# CMD yarn run dev
# CMD  yarn start:dev